project_name: waitfor
before:
  hooks:
    - go mod tidy
    - rm -rf dist
    - gofumpt -l -w .
builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    goarm:
      - "7"
    ldflags:
      - -s -w -X=github.com/ebarped/waitfor/main.Version={{.Version}} # go tool link flags
archives:
  - format_overrides:
    replacements:
      linux: Linux
      amd64: x86_64
release:
snapshot:
  name_template: "{{ .Tag }}-next"

